# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado/MUL_CPU_2/MUL_CPU_2.cache/wt [current_project]
set_property parent.project_path D:/vivado/MUL_CPU_2/MUL_CPU_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado/MUL_CPU_2/MUL_CPU_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/7_SegLED.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/ALU.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/D_state.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/D_trigger.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Data_Memory.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Get_Address.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Get_Op.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Get_State.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Ins_Memory.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Ins_Reg.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/MUX3.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/MUX32.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/MUX532.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Mul_CPU.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/PC.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/PC_Add.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/PC_Jump.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/PC_branch.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Regfile.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/Sign_extend.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/control.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/display.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/getclk.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/getdata.v
  D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/sources_1/new/solve.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/constrs_1/new/MUL_CPU.xdc
set_property used_in_implementation false [get_files D:/vivado/MUL_CPU_2/MUL_CPU_2.srcs/constrs_1/new/MUL_CPU.xdc]


synth_design -top solve -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef solve.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file solve_utilization_synth.rpt -pb solve_utilization_synth.pb"
