webtalk_init -webtalk_dir D:/vivado/Single_CPU_2/Single_CPU_2.sim/sim_1/behav/xsim/xsim.dir/solve_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 21 02:02:03 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "89abff15-f65e-48e5-a284-77e2e801eb81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2ae58fb8d6a64d889e6007831345be57" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "55" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3286680295 -regid "" -xml D:/vivado/Single_CPU_2/Single_CPU_2.sim/sim_1/behav/xsim/xsim.dir/solve_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/vivado/Single_CPU_2/Single_CPU_2.sim/sim_1/behav/xsim/xsim.dir/solve_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/vivado/Single_CPU_2/Single_CPU_2.sim/sim_1/behav/xsim/xsim.dir/solve_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
